services:
  database:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - ./src/db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lovememo
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    environment:
      - HTTPS=true
      - SSL_KEY=/etc/ssl/private/localhost-key.pem
      - SSL_CERT=/etc/ssl/private/localhost.pem
    ports:
      - "3000:3000"
      - "3443:3443"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - ./ssl:/etc/ssl/private
    networks:
      - lovememo
    depends_on:
      database:
        condition: service_healthy
    command: yarn start:debug

volumes:
  db_data:
networks:
  lovememo:
    driver: bridge
